SELECT
  CONCAT(a.AD_ID, '_', a.USER_SEGMENT_KEY) AS UNIQUE_ID, -- Unique ID column
  m.OS_MERCHANT,
  a.USER_SEGMENT_KEY,
  a.AD_ID,
  a.ACCOUNT_ID,
  SUM(a.SPEND) AS TOTAL_SPEND,
  SUM(a.CONVERSIONS) AS TOTAL_CONVERSIONS
FROM ANALYTICS.MAIN_OS.FACEBOOK_USER_SEGMENT_ADS_ADAPTER a
LEFT JOIN ANALYTICS.MAIN_OS.OS_MERCHANTS m
  ON a.os_store_id = m.os_store_id
WHERE m.IS_CLOSED
  AND a.CONVERSIONS IS NOT NULL
  AND a.OS_DT >= DATEADD(MONTH, -12, CURRENT_DATE)
GROUP BY
  CONCAT(a.AD_ID, '_', a.USER_SEGMENT_KEY),
  m.OS_MERCHANT,
  a.USER_SEGMENT_KEY,
  a.AD_ID,
  a.ACCOUNT_ID
ORDER BY a.AD_ID DESC;